# 服务配置
server:
  port: 8080
  shutdown: graceful

# 日志级别配置
logging:
  level:
    com.shop_service: debug

# spring配置
spring:
  # 请求配置
  servlet:
    multipart:
      # 单个文件最大限制
      max-file-size: 20MB
      # 总请求体最大限制 (所有文件加表单)
      max-request-size: 20MB
  # 序列化配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  # redis配置
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      password:
  # mysql配置
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/uk_shop_service?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useUnicode=yes
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: mysql
      connection-test-query: SELECT 1
  # springboot admin 配置
  boot:
    admin:
      client:
        url:

# mybatis-plus配置
mybatis-plus:
  # xml位置
  mapper-locations: classpath:mapper-xml/**/*.xml

# redisson 配置
redisson:
  address: redis://127.0.0.1:6379
  database: 0

# actuator 配置
management:
  endpoints:
    web:
      # 开启监控所有项
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

# 系统配置
system:
  domain: http://127.0.0.1:8080
  admin-token: 73c3632d-e7de-4865-9c28-3dd966d59f29

# 波场配置
tron:
  api: https://tron.vdo6ec.cn
  id: 9
  key: 6e5e210c-8e4a-4a00-9c35-0ff3658137fa

# vs卡片服务配置
vs:
  api: http://127.0.0.1:8081
  token: 28abbd65-14a4-42cf-85fe-6b4583957e5f